# Generated by Django 3.2.6 on 2021-09-05 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210904_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='thumbnail_image',
            new_name='product_image',
        ),
    ]
