# Generated by Django 3.2.6 on 2021-09-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210911_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_key',
            field=models.CharField(default='chair', max_length=250),
            preserve_default=False,
        ),
    ]
