# Generated by Django 3.2.6 on 2021-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_search_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_image2',
            field=models.ImageField(default='2.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
