# Generated by Django 3.2.6 on 2021-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_thumbnail_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_images1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
