# Generated by Django 3.2.6 on 2021-09-21 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210916_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinquiry',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
