# Generated by Django 3.2.6 on 2021-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
