# Generated by Django 3.2.6 on 2021-09-05 08:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('desc', ckeditor.fields.RichTextField()),
                ('category', models.CharField(max_length=200)),
                ('thumbnail_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
