# Generated by Django 3.2.6 on 2021-09-21 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 5, 13, 33, 999552)),
        ),
    ]
