# Generated by Django 3.2.6 on 2021-09-21 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 5, 14, 57, 611264)),
        ),
    ]
