# Generated by Django 3.2.6 on 2021-09-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
